// models/care_test_request_blood.js
'use strict';
const { DataTypes } = require('sequelize');

module.exports = (sequelize) => {
  const care_test_request_blood = sequelize.define('care_test_request_blood', {
    batch_nr: { type: DataTypes.STRING, primaryKey: true, autoIncrement: true },
    encounter_nr: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false, defaultValue: 0 },
    dept_nr: { type: DataTypes.SMALLINT.UNSIGNED, allowNull: false, defaultValue: 0 },
    blood_group: { type: DataTypes.STRING(10), allowNull: false, defaultValue: '' },
    rh_factor: { type: DataTypes.STRING(10), allowNull: false, defaultValue: '' },
    kell: { type: DataTypes.STRING(10), allowNull: false, defaultValue: '' },
    date_protoc_nr: { type: DataTypes.STRING(45), allowNull: false, defaultValue: '' },
    pure_blood: { type: DataTypes.STRING(15), allowNull: false, defaultValue: '' },
    red_blood: { type: DataTypes.STRING(15), allowNull: false, defaultValue: '' },
    leukoless_blood: { type: DataTypes.STRING(15), allowNull: false, defaultValue: '' },
    washed_blood: { type: DataTypes.STRING(15), allowNull: false, defaultValue: '' },
    prp_blood: { type: DataTypes.STRING(15), allowNull: false, defaultValue: '' },
    thrombo_con: { type: DataTypes.STRING(15), allowNull: false, defaultValue: '' },
    ffp_plasma: { type: DataTypes.STRING(15), allowNull: false, defaultValue: '' },
    transfusion_dev: { type: DataTypes.STRING(15), allowNull: false, defaultValue: '' },
    match_sample: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    transfusion_date: { type: DataTypes.DATEONLY, allowNull: true },
    diagnosis: { type: DataTypes.TEXT, allowNull: false },
    notes: { type: DataTypes.TEXT, allowNull: false },
    send_date: { type: DataTypes.DATEONLY, allowNull: true },
    doctor: { type: DataTypes.STRING(35), allowNull: false, defaultValue: '' },
    phone_nr: { type: DataTypes.STRING(40), allowNull: false, defaultValue: '' },
    status: { type: DataTypes.STRING(10), allowNull: false, defaultValue: '' },
    blood_pb: { type: DataTypes.TEXT, allowNull: false },
    blood_rb: { type: DataTypes.TEXT, allowNull: false },
    blood_llrb: { type: DataTypes.TEXT, allowNull: false },
    blood_wrb: { type: DataTypes.TEXT, allowNull: false },
    blood_prp: { type: DataTypes.STRING, allowNull: false },
    blood_tc: { type: DataTypes.TEXT, allowNull: false },
    blood_ffp: { type: DataTypes.TEXT, allowNull: false },
    b_group_count: { type: DataTypes.MEDIUMINT, allowNull: false, defaultValue: 0 },
    b_group_price: { type: DataTypes.FLOAT, allowNull: false, defaultValue: '0.00' },
    a_subgroup_count: { type: DataTypes.MEDIUMINT, allowNull: false, defaultValue: 0 },
    a_subgroup_price: { type: DataTypes.FLOAT, allowNull: false, defaultValue: '0.00' },
    extra_factors_count: { type: DataTypes.MEDIUMINT, allowNull: false, defaultValue: 0 },
    extra_factors_price: { type: DataTypes.FLOAT, allowNull: false, defaultValue: '0.00' },
    coombs_count: { type: DataTypes.MEDIUMINT, allowNull: false, defaultValue: 0 },
    coombs_price: { type: DataTypes.FLOAT, allowNull: false, defaultValue: '0.00' },
    ab_test_count: { type: DataTypes.MEDIUMINT, allowNull: false, defaultValue: 0 },
    ab_test_price: { type: DataTypes.FLOAT, allowNull: false, defaultValue: '0.00' },
    crosstest_count: { type: DataTypes.MEDIUMINT, allowNull: false, defaultValue: 0 },
    crosstest_price: { type: DataTypes.FLOAT, allowNull: false, defaultValue: '0.00' },
    ab_diff_count: { type: DataTypes.MEDIUMINT, allowNull: false, defaultValue: 0 },
    ab_diff_price: { type: DataTypes.FLOAT, allowNull: false, defaultValue: '0.00' },
    x_test_1_code: { type: DataTypes.MEDIUMINT, allowNull: false, defaultValue: 0 },
    x_test_1_name: { type: DataTypes.STRING(35), allowNull: false, defaultValue: '' },
    x_test_1_count: { type: DataTypes.MEDIUMINT, allowNull: false, defaultValue: 0 },
    x_test_1_price: { type: DataTypes.FLOAT, allowNull: false, defaultValue: '0.00' },
    x_test_2_code: { type: DataTypes.MEDIUMINT, allowNull: false, defaultValue: 0 },
    x_test_2_name: { type: DataTypes.STRING(35), allowNull: false, defaultValue: '' },
    x_test_2_count: { type: DataTypes.MEDIUMINT, allowNull: false, defaultValue: 0 },
    x_test_2_price: { type: DataTypes.FLOAT, allowNull: false, defaultValue: '0.00' },
    x_test_3_code: { type: DataTypes.MEDIUMINT, allowNull: false, defaultValue: 0 },
    x_test_3_name: { type: DataTypes.STRING(35), allowNull: false, defaultValue: '' },
    x_test_3_count: { type: DataTypes.MEDIUMINT, allowNull: false, defaultValue: 0 },
    x_test_3_price: { type: DataTypes.FLOAT, allowNull: false, defaultValue: '0.00' },
    lab_stamp: { type: DataTypes.DATE, allowNull: true },
    release_via: { type: DataTypes.STRING(20), allowNull: false, defaultValue: '' },
    receipt_ack: { type: DataTypes.STRING(20), allowNull: false, defaultValue: '' },
    mainlog_nr: { type: DataTypes.STRING(7), allowNull: false, defaultValue: '' },
    lab_nr: { type: DataTypes.STRING(7), allowNull: false, defaultValue: '' },
    mainlog_date: { type: DataTypes.DATEONLY, allowNull: true },
    lab_date: { type: DataTypes.DATEONLY, allowNull: true },
    mainlog_sign: { type: DataTypes.STRING(20), allowNull: false, defaultValue: '' },
    lab_sign: { type: DataTypes.STRING(20), allowNull: false, defaultValue: '' },
    history: { type: DataTypes.TEXT, allowNull: true },
    modify_id: { type: DataTypes.STRING(35), allowNull: false, defaultValue: '' },
    modify_time: { type: DataTypes.DATE, allowNull: false },
    create_id: { type: DataTypes.STRING(35), allowNull: false, defaultValue: '' },
    create_time: { type: DataTypes.DATE, allowNull: false },
  }, {
    tableName:  'care_test_request_blood',
    timestamps: false,
  });

  return care_test_request_blood;
};